sim/mahasiswa/routes.py
from flask import Flask, render_template, redirect, request, url_for, Blueprint, flash, request
from sim.mahasiswa.forms import mahasiswa_F, loginmahasiswa_F, editmahasiswa_F, pengaduan_F, editpengaduan_F, pendataan_F, editpendataan_F
from sim.models import Tmahasiswa, Tpengaduan, Tpendataan
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image

rmahasiswa= Blueprint('rmahasiswa', __name__)

@rmahasiswa.route("/")
def home():
    return render_template("home.html")

@rmahasiswa.route("/about")
def about():
    return render_template("about.html")

@rmahasiswa.route("/registration")
def registration():
    return render_template("registration.html")

@rmahasiswa.route("/data_mahasiswa", methods=['GET', 'POST'])
def data_m():
    form=mahasiswa_F()
    if form.validate_on_submit():
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode("UTF-8")
        add_mahasiswa=Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data, 
        password=pass_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun- {form.npm.data} berhasil daftar', 'info')
        return redirect(url_for('rmahasiswa.login_mahasiswa'))
    return render_template("data-mahasiswa.html", form=form)

@rmahasiswa.route("/login_mahasiswa", methods=['GET', 'POST'])
def login_mahasiswa():
    if current_user.is_authenticated:
        return redirect(url_for('rmahasiswa.home'))
    form=loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm=Tmahasiswa.query.filter_by(npm=form.npm.data). first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('Selamat Datang Kembali', 'warning')
            return redirect(url_for('rmahasiswa.akunmahasiswa'))
        else:
            flash('Login Gagal, Periksa NPM dan Password kembali', 'danger')
    return render_template("login_mahasiswa.html", form=form)

@rmahasiswa.route("/akunmahasiswa")
@login_required
def akunmahasiswa():
    return render_template('akunmahasiswa.html')

@rmahasiswa.route("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('rmahasiswa.home'))

#simpan foto
def simpan_foto(form_foto):
    random_hex= secrets.token_hex(8)
    f_name, f_exit=os.path.splitext(form_foto.filename)
    foto_fn= random_hex + f_exit
    foto_path= os.path.join(app.root_path, 'sim/static/Gambar', foto_fn)
    ubah_size=(300, 300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn

@rmahasiswa.route("/edit_mahasiswa", methods=['GET', 'POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto=file_foto
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode("UTF-8")
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        current_user.password=pass_hash
        db.session.commit()
        flash('Data berhasil diubah', 'warning')
        return redirect(url_for('rmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
        form.npm.data= current_user.npm
        form.nama.data=current_user.nama
        form.email.data=current_user.email
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat
    return render_template('edit_mahasiswa.html', form=form)


@rmahasiswa.route("/pengaduan", methods=['GET', 'POST'])
@login_required
def pengaduan():
    dt_pengaduan=Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F() 
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pengaduan=Tpengaduan(subjek=form.subjek.data, kategori=form.kategori.data, detail_pengaduan=form.detail_pengaduan.data,
        mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data berhasil ditambahkan', 'warning')
        return redirect(url_for('rmahasiswa.pengaduan'))

    return render_template('pengaduan.html', form=form, dt_pengaduan=dt_pengaduan)

@rmahasiswa.route("/pengaduan/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pengaduan(ed_id):
    form=editpengaduan_F()
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan

    elif form.validate_on_submit():
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.kategori=form.kategori.data
        dt_pengaduan.detail_pengaduan=form.detail_pengaduan.data
        db.session.commit()
        flash('Data berhasil diubah', 'warning')
        return redirect(url_for('rmahasiswa.pengaduan'))

    return render_template('edit_pengaduan.html', form=form)

@rmahasiswa.route("/delete/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pengaduan(id):
    h_pengaduan=Tpengaduan.query.get(id)
    db.session.delete(h_pengaduan)
    db.session.commit()
    flash('Data berhasil dihapus', 'warning')
    return redirect(url_for('rmahasiswa.pengaduan'))

@rmahasiswa.route("/pengaduan/<int:ed_id>/detail", methods=['GET', 'POST'])
@login_required
def detail_pengaduan(ed_id):
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    return render_template('detail_pengaduan.html', dt_pengaduan=dt_pengaduan)

@rmahasiswa.route("/pendataan", methods=['GET', 'POST'])
@login_required
def pendataan():
    dt_pendataan=Tpendataan.query.filter_by(mahasiswa_id=current_user.id)
    form=pendataan_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pendataan=Tpendataan(kategori_surat=form.kategori_surat.data, surat=form.surat.data, detail_surat=form.detail_surat.data, 
        mahasiswas=current_user)
        db.session.add(add_pendataan)
        db.session.commit()
        flash('Data berhasil ditambahkan', 'warning')
        return redirect(url_for('rmahasiswa.pendataan'))

    return render_template('pendataan.html', form=form, dt_pendataan=dt_pendataan)

@rmahasiswa.route("/pendataan/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pendataan(ed_id):
    form=editpendataan_F()
    dt_pendataan=Tpendataan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.kategori_surat.data=dt_pendataan.kategori_surat
        form.surat.data=dt_pendataan.surat
        form.detail_surat.data=dt_pendataan.detail_surat

    elif form.validate_on_submit():
        dt_pendataan.kategori_surat=form.kategori_surat.data
        dt_pendataan.surat=form.surat.data
        dt_pendataan.detail_surat=form.detail_surat.data
        db.session.commit()
        flash('Data berhasil diubah', 'warning')
        return redirect(url_for('rmahasiswa.pendataan'))

    return render_template('edit_pendataan.html', form=form)

@rmahasiswa.route("/delete1/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pendataan(id):
    h_pendataan=Tpendataan.query.get(id)
    db.session.delete(h_pendataan)
    db.session.commit()
    flash('Data berhasil dihapus', 'warning')
    return redirect(url_for('rmahasiswa.pendataan'))


@rmahasiswa.route("/artikel/<info>")
def artikel_info(info):
    return "Halaman Artikel " + info;

sim/templates/about.html
{%extends "base.html"%}



{%block konten%}
<h1>About Us</h1>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse perspiciatis ipsa veniam, fugiat reiciendis ab inventore nemo molestiae voluptas, laudantium quidem eum eligendi. Animi rem reiciendis a laboriosam minus dolore.</p>

{%endblock%}

sim/templates/akunmahasiswa.html
{%extends "base.html"%}



{%block konten%}
<div class="jumbotron">
    <h1 class="display-4">Hello, {{current_user.nama}}</h1>
    <p class="leat">Selamat Datang di Distem Informasi Pengaduan. Semoga segala pengaduan anda menjadi perbaikan kami</p>
    <hr class="my-4">
    <p>Kilk untuk memulai pengaduan anda</p>
    <a href="{{url_for('rmahasiswa.pengaduan')}}" class="btn btn-primary btn-lg" role="button">Pengaduan</a>
</div>

{%endblock%}

sim/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZENIUS</title>
    <link href="{{url_for ('static', filename='css/bootstrap.min.css')}}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for ('static', filename='css/style.css')}}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <div class="container-md">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ZENIUS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('rmahasiswa.home')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('rmahasiswa.about')}}">About</a>
              </li>
              {% if current_user.is_authenticated %}
             
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('rmahasiswa.login_mahasiswa')}}">Login Mahasiswa</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('rmahasiswa.registration')}}">Registrasi</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </div>
    </nav>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                <div class="shadow p-3 mb-5 bg-body rounded">
                <!---flash---->
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}

                <div class="alert alert-{{category}}">
                {{message}} 
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}

                {%block konten%}


                {%endblock%}
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow p-3 mb-5 bg-body rounded">
                
                {% if current_user.is_authenticated %}
                <div class="card" style="width: 23,5rem;">
                  <img src="{{url_for('static', filename='Gambar/' + current_user.foto)}}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{current_user.nama}}</h5>
                    <p class="card-text">{{current_user.email}}</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.akunmahasiswa')}}">Dasboard</a></li> 
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.pengaduan')}}">Pengaduan</a></li>
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.pendataan')}}">Pendataan Surat</a></li>
                  </ul>
                  <div class="card-body">
                    <a href="{{url_for('rmahasiswa.edit_mahasiswa')}}" class="card-link">Update Profil</a>
                    <a href="{{url_for('rmahasiswa.logout_mahasiswa')}}" class="card-link">Logout</a>
                  </div>
                </div>
                {% else %}
                <h1>Menu Lain</h1>
                <li>Data Mahasiswa</li>
                <li>Data Dosen</li>
                {% endif %}
                
                </div>
            </div> 
        </div>  
    </div>
    
</body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="{{url_for ('static', filename='js/bootstrap.min.js')}}" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</html>

sim/templates/data-mahasiswa.html
{%extends "base.html"%}


{%block konten%}

<h1>Daftar Akun</h1>
<form method="POST">
        {{form.hidden_tag()}}
    <div class="from-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
            {{form.npm(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.npm.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.npm(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>
    <div class="from-group">
        {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
            {{form.email(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
        {{form.email(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.kelas.label(class="form-control-label")}}
        {% if form.kelas.errors %}
            {{form.kelas(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.kelas.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.kelas(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.alamat.label(class="form-control-label")}}
        {{form.alamat(class="form-control")}}
    </div>
    <div class="from-group">
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{errors}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.password(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.konf_pass.label(class="form-control-label")}}
        {% if form.konf_pass.errors %}
            {{form.konf_pass(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.konf_pass.errors %}
                <span>{{errors}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.konf_pass(class="form-control")}}
        {% endif %}
    </div>
    <br>
    <div class="group-form">
        {{form.submit(class="btn btn-primary")}}
    </div>
</form>


{%endblock%}

    
    
 

sim/templates/detail_pengaduan.html
{%extends "base.html"%}



{%block konten%}

<h3>Detail Pengaduan</h3>
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Well done!</h4>
    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
    <hr>
    
    <!--Table-->
    <table class="table table-hover">
        <tr>
            <td>NPM</td>
            <td>{{dt_pengaduan.mahasiswa.npm}}</td>
        </tr>
        <tr>
            <td>Nama</td>
            <td>{{dt_pengaduan.mahasiswa.nama}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{dt_pengaduan.mahasiswa.email}}</td>
        </tr>
        <tr>
            <td>Kelas</td>
            <td>{{dt_pengaduan.mahasiswa.kelas}}</td>
        </tr>
        <tr>
            <td>Alamat</td>
            <td>{{dt_pengaduan.mahasiswa.alamat}}</td>
        </tr>

    </table>
</div>

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Data Pengaduan</h4>
    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
    <hr>
    <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>

    <table class="table table-hover">
    <tr>
        <td>Tgl Post</td>
        <td>{{dt_pengaduan.tgl_post}}</td>
    </tr>
    <tr>
        <td>Subjek</td>
        <td>{{dt_pengaduan.subjek}}</td>
    </tr>
    <tr>
        <td>Kategori</td>
        <td>{{dt_pengaduan.kategori}}</td>
    </tr>
    <tr>
        <td>Pengaduan :</td>   
    </tr>
    <tr>
        <td>{{dt_pengaduan.detail_pengaduan}}</td>
    </tr>
    </table>
</div>

<a class="btn btn-secondary" href="{{url_for('rmahasiswa.pengaduan')}}">Kembali</a>

{%endblock%}

sim/templates/login_mahasiswa.html
{%extends "base.html"%}


{%block konten%}

<h1>Login Mahasiswa</h1>
<form method="POST">
        {{form.hidden_tag()}}
    <div class="from-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
            {{form.npm(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.npm.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.npm(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.password(class="form-control")}}
        {% endif %}
    </div>
    <br>
    <div class="group-form">
        {{form.submit(class="btn btn-primary")}}
    </div>

    <span><a href="{{url_for('rmahasiswa.data_m')}}">Daftar Akun</a></span>
</form>


{%endblock%}

    
    
 

sim/templates/pendataan.html
{%extends "base.html"%}



{%block konten%}
<div class="jumbotron">

    <h3>Pendataan Surat</h3>
    <!---form pengaduan-->

    <form method="POST">
        {{form.hidden_tag()}}
    <div class="from-group">
        {{form.kategori_surat.label(class="form-control-label")}}
        {% if form.kategori_surat.errors %}
            {{form.kategori_surat(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.kategori_surat.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.kategori_surat(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.surat.label(class="form-control-label")}}
        {% if form.surat.errors %}
            {{form.surat(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.surat.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.surat(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.detail_surat.label(class="form-control-label")}}
        {% if form.detail_surat.errors %}
            {{form.detail_surat(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.detail_surat.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.detail_surat(class="form-control")}}
        {% endif %}
    </div>
    
    <br>
    <div class="group-form">
        {{form.submit(class="btn btn-primary")}}
    </div>
</form>

<hr class="my-4">
    <h4>Pendataan Surat</h4>
    <div class="table-responsive">
    <table class="table table-hover table-info">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tgl</th>
                <th scope="col">Kategori Surat</th>
                <th scope="col">Surat</th>
                <th scope="col">Detail Surat</th>
                <th scope="col">Edit</th>
                <th scope="col">Hapus</th>
            </tr>
        </thead>
        <tbody>
            {% for data in dt_pendataan %}
            <tr>
                <th>#</th>
                <td>{{data.tgl_surat}}</td>
                <td>{{data.kategori_surat}}</td>
                <td>{{data.surat}}</td>  
                <td>{{data.detail_surat}}</td>  
                <td><a class="btn btn-outline-warning" href="{{url_for('rmahasiswa.update_pendataan', ed_id=data.id)}}">Edit</a></td>
                <td><a class="btn btn-outline-danger" href="/delete1/{{data.id}}" onclick="return confirm('Yakin data dihapus')"> Hapus</a></td>
            </tr>
            {% endfor %}
            <!---modals hapus-->

            <!--div class="modal" tabindex="-1" role="dialog" id="modals-hapus">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Konfirmasi Hapus</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p>Apakah anda yakin menghapus data ini</p>
                    </div>
                    <div class="modal-footer">
                    <form action="">
                        <a class="btn btn-warning" id="del-hapus">Hapus</a>
                    </form>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> 
                    </div>
                  </div>
                </div>
              </div-->
        </tbody>
    </table>
    </div>
</div>


{% endblock %}

sim/templates/pengaduan.html
{%extends "base.html"%}



{%block konten%}
<div class="jumbotron">

    <h3>Pengaduan</h3>
    <!---form pengaduan-->

    <form method="POST">
        {{form.hidden_tag()}}
    <div class="from-group">
        {{form.subjek.label(class="form-control-label")}}
        {% if form.subjek.errors %}
            {{form.subjek(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.subjek(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.kategori.label(class="form-control-label")}}
        {% if form.kategori.errors %}
            {{form.kategori(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.kategori.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.kategori(class="form-control")}}
        {% endif %}
    </div>
    <div class="from-group">
        {{form.detail_pengaduan.label(class="form-control-label")}}
        {% if form.detail_pengaduan.errors %}
            {{form.detail_pengaduan(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {% for error in form.detail_pengaduan.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.detail_pengaduan(class="form-control")}}
        {% endif %}
    </div>
    
    <br>
    <div class="group-form">
        {{form.submit(class="btn btn-primary")}}
    </div>
</form>

<!--script>
    function klik_hapus(value){
        let valid_link = document.getElementById('del-hapus')
        valid_link.href="/delete/"+ value
    }
</script-->

    <hr class="my-4">
    <h4>Data Pengaduan</h4>
    <div class="table-responsive">
    <table class="table table-hover table-info">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tgl</th>
                <th scope="col">Subjek</th>
                <th scope="col">Kategori</th>
                <th scope="col">Edit</th>
                <th scope="col">Hapus</th>
            </tr>
        </thead>
        <tbody>
            {% for data in dt_pengaduan %}
            <tr>
                <th>
                    <a href="{{url_for('rmahasiswa.detail_pengaduan', ed_id=data.id)}}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up-left-square-fill" viewBox="0 0 16 16">
                            <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm8.096 10.803L6 6.707v2.768a.5.5 0 0 1-1 0V5.5a.5.5 0 0 1 .5-.5h3.975a.5.5 0 1 1 0 1H6.707l4.096 4.096a.5.5 0 1 1-.707.707z"/>
                        </svg>
                    </a>
                </th>
                <td>{{data.tgl_post}}</td>
                <td>{{data.subjek}}</td>
                <td>{{data.kategori}}</td>  
                <td><a class="btn btn-outline-warning" href="{{url_for('rmahasiswa.update_pengaduan', ed_id=data.id)}}">Edit</a></td>
                <td><a class="btn btn-outline-danger" href="/delete/{{data.id}}" onclick="return confirm('Yakin data dihapus')"> Hapus</a></td>
            </tr>
            {% endfor %}
            <!---modals hapus-->

            <!--div class="modal" tabindex="-1" role="dialog" id="modals-hapus">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Konfirmasi Hapus</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p>Apakah anda yakin menghapus data ini</p>
                    </div>
                    <div class="modal-footer">
                    <form action="">
                        <a class="btn btn-warning" id="del-hapus">Hapus</a>
                    </form>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> 
                    </div>
                  </div>
                </div>
              </div-->
        </tbody>
    </table>
    </div>
</div>

{% endblock %}